COURSES = {
    1: {"title": "第一次见面！", "topic": "打招呼", "new_words": "Hello / Hi / Bye bye", "review": "无", "game": "自我介绍"},
    2: {"title": "我叫什么名字", "topic": "自我介绍", "new_words": "My name is ___", "review": "Hello / Bye", "game": "名字接龙"},
    3: {"title": "你好吗？", "topic": "问候", "new_words": "How are you? / I'm fine!", "review": "前两课", "game": "情绪卡片"},
    4: {"title": "认识新朋友", "topic": "社交", "new_words": "Nice to meet you!", "review": "前三课串联", "game": "交友情景"},
    5: {"title": "第一周大复习", "topic": "综合复习", "new_words": "场景游戏串联全周内容", "review": "第1-4课所有内容", "game": "开心动物派对"},
    6: {"title": "神奇数字1-3", "topic": "数字", "new_words": "One, Two, Three", "review": "打招呼", "game": "用手指数苹果"},
    7: {"title": "继续数！4-6", "topic": "数字", "new_words": "Four, Five, Six", "review": "数字1-3", "game": "数积木游戏"},
    8: {"title": "冲刺7-10！", "topic": "数字", "new_words": "Seven, Eight, Nine, Ten", "review": "数字1-6", "game": "数星星"},
    9: {"title": "数字大连线", "topic": "数字复习", "new_words": "1-10 完整回顾", "review": "数字1-10", "game": "数字歌游戏"},
    10: {"title": "第二周复习", "topic": "综合复习", "new_words": "打招呼+数字综合", "review": "第6-9课", "game": "几只动物来敲门"},
    11: {"title": "红黄蓝！三原色", "topic": "颜色", "new_words": "Red, Yellow, Blue", "review": "数字", "game": "找家里的红色东西"},
    12: {"title": "绿黑白", "topic": "颜色", "new_words": "Green, Black, White", "review": "Red/Yellow/Blue", "game": "涂色游戏"},
    13: {"title": "橙紫粉", "topic": "颜色", "new_words": "Orange, Purple, Pink", "review": "前面颜色", "game": "彩虹颜色连线"},
    14: {"title": "颜色全掌握", "topic": "颜色复习", "new_words": "所有颜色复习", "review": "全部颜色", "game": "我看到一个___颜色"},
    15: {"title": "第三周复习", "topic": "综合复习", "new_words": "数字+颜色综合", "review": "第11-14课", "game": "几个红苹果？"},
    16: {"title": "打招呼全复习", "topic": "第一阶段复习", "new_words": "打招呼场景练习", "review": "第1-5课", "game": "开心动物派对"},
    17: {"title": "数字全复习", "topic": "第一阶段复习", "new_words": "数字1-10场景练习", "review": "第6-10课", "game": "魔法数字宝藏"},
    18: {"title": "颜色全复习", "topic": "第一阶段复习", "new_words": "颜色场景练习", "review": "第11-15课", "game": "彩虹魔法师"},
    19: {"title": "打招呼+数字+颜色", "topic": "第一阶段复习", "new_words": "三大主题综合", "review": "第1-15课", "game": "超市买东西"},
    20: {"title": "阶段庆典课", "topic": "阶段总结", "new_words": "AI总结孩子一个月进步", "review": "第1-19课", "game": "颁奖典礼"},
    21: {"title": "A, B, C", "topic": "字母A-G", "new_words": "Apple苹果 / Ball球 / Cat猫", "review": "颜色", "game": "字母找朋友"},
    22: {"title": "D, E, F", "topic": "字母A-G", "new_words": "Dog狗 / Egg蛋 / Fish鱼", "review": "A B C", "game": "字母童谣歌唱"},
    23: {"title": "G + A-G复习", "topic": "字母A-G", "new_words": "Girl女孩 / A-G字母歌", "review": "A B C D E F", "game": "字母接龙"},
    24: {"title": "A-G 情境复习", "topic": "字母复习", "new_words": "在故事中找字母", "review": "A-G全部", "game": "小猫的一天故事"},
    25: {"title": "A-G 强化游戏", "topic": "字母强化", "new_words": "字母猜谜", "review": "A-G全部", "game": "我想到了一个字母"},
    26: {"title": "H, I, J", "topic": "字母H-N", "new_words": "Hat帽子 / Ice冰淇淋 / Jump跳", "review": "A-G", "game": "做动作"},
    27: {"title": "K, L, M", "topic": "字母H-N", "new_words": "Key钥匙 / Lion狮子 / Moon月亮", "review": "H I J", "game": "字母故事"},
    28: {"title": "N + H-N复习", "topic": "字母H-N", "new_words": "Nose鼻子", "review": "H-N全部", "game": "身体部位字母歌"},
    29: {"title": "H-N 情境复习", "topic": "字母复习", "new_words": "小猫夜晚冒险故事", "review": "H-N全部", "game": "故事游戏"},
    30: {"title": "A-N 大串讲", "topic": "字母总复习", "new_words": "字母歌完整版前半段", "review": "A-N全部", "game": "字母歌比赛"},
    31: {"title": "O, P, Q", "topic": "字母O-U", "new_words": "Orange橙子 / Pig猪 / Queen女王", "review": "A-N", "game": "字母王国"},
    32: {"title": "R, S, T", "topic": "字母O-U", "new_words": "Rain雨 / Sun太阳 / Tiger老虎", "review": "O P Q", "game": "天气字母"},
    33: {"title": "U + O-U复习", "topic": "字母O-U", "new_words": "Umbrella雨伞", "review": "O-U全部", "game": "下雨天场景"},
    34: {"title": "O-U 情境故事", "topic": "字母复习", "new_words": "小猪的雨天冒险", "review": "O-U全部", "game": "故事角色扮演"},
    35: {"title": "A-U 大复习", "topic": "字母总复习", "new_words": "字母歌完整前20个", "review": "A-U全部", "game": "字母接龙比赛"},
    36: {"title": "V, W, X", "topic": "字母V-Z", "new_words": "Violin小提琴 / Watermelon西瓜 / X-ray", "review": "A-U", "game": "神奇字母"},
    37: {"title": "Y, Z + 收尾", "topic": "字母V-Z", "new_words": "Yo-yo悠悠球 / Zebra斑马", "review": "V W X", "game": "动物园"},
    38: {"title": "26字母完整歌", "topic": "字母总复习", "new_words": "字母歌完整版", "review": "A-Z全部", "game": "字母大合唱"},
    39: {"title": "字母综合游戏", "topic": "字母总复习", "new_words": "26字母全部复习", "review": "A-Z全部", "game": "字母宝藏游戏"},
    40: {"title": "第二阶段庆典", "topic": "阶段总结", "new_words": "颁发字母小达人", "review": "第21-39课", "game": "字母知识大闯关"},
    41: {"title": "Mom / Dad", "topic": "家庭成员", "new_words": "This is my mom. / This is my dad.", "review": "字母", "game": "介绍家人"},
    42: {"title": "Brother / Sister / Baby", "topic": "家庭成员", "new_words": "I have a sister.", "review": "Mom/Dad", "game": "家庭相册"},
    43: {"title": "Grandma / Grandpa", "topic": "家庭成员", "new_words": "My grandma is nice.", "review": "全部家庭成员", "game": "拜访祖父母"},
    44: {"title": "家庭大复习", "topic": "家庭复习", "new_words": "全家福场景", "review": "第41-43课", "game": "我的家小作文口述"},
    45: {"title": "字母+家庭综合", "topic": "综合", "new_words": "用字母说家人名字", "review": "字母+家庭", "game": "家人名字字母"},
    46: {"title": "Head / Hair / Face", "topic": "身体部位", "new_words": "Touch your head!", "review": "家庭", "game": "指一指互动游戏"},
    47: {"title": "Eyes / Nose / Mouth / Ears", "topic": "身体部位", "new_words": "I have two eyes.", "review": "Head/Hair/Face", "game": "五官歌"},
    48: {"title": "Hands / Fingers / Feet", "topic": "身体部位", "new_words": "Clap your hands!", "review": "前面身体部位", "game": "Head Shoulders歌"},
    49: {"title": "Tummy / Back / Legs", "topic": "身体部位", "new_words": "My legs are strong!", "review": "全部身体部位", "game": "机器人角色扮演"},
    50: {"title": "身体部位大复习", "topic": "身体复习", "new_words": "Simon Says游戏", "review": "第46-49课", "game": "指令游戏"},
    51: {"title": "Apple / Banana / Orange", "topic": "食物饮料", "new_words": "I like apples!", "review": "身体部位", "game": "水果超市"},
    52: {"title": "Rice / Bread / Egg", "topic": "食物饮料", "new_words": "I eat rice every day.", "review": "水果词汇", "game": "早餐时间"},
    53: {"title": "Milk / Water / Juice", "topic": "食物饮料", "new_words": "I want milk please.", "review": "主食词汇", "game": "小餐厅点单"},
    54: {"title": "Cake / Cookie / Ice cream", "topic": "食物饮料", "new_words": "It's delicious!", "review": "饮料词汇", "game": "生日派对"},
    55: {"title": "食物大复习", "topic": "食物复习", "new_words": "I don't like___句型", "review": "第51-54课", "game": "食物喜好调查"},
    56: {"title": "Cat / Dog / Fish", "topic": "动物", "new_words": "I have a dog.", "review": "食物", "game": "宠物店"},
    57: {"title": "Rabbit / Bird / Monkey", "topic": "动物", "new_words": "The monkey is funny!", "review": "宠物词汇", "game": "动物园"},
    58: {"title": "Lion / Elephant / Tiger", "topic": "动物", "new_words": "The elephant is big.", "review": "小动物词汇", "game": "丛林探险"},
    59: {"title": "动物叫声", "topic": "动物", "new_words": "The cat says meow.", "review": "全部动物", "game": "动物猜谜"},
    60: {"title": "第三阶段大复习", "topic": "阶段总结", "new_words": "家庭+身体+食物+动物综合", "review": "第41-59课", "game": "大富翁词汇游戏"},
    61: {"title": "This is a ___.", "topic": "句型This is", "new_words": "This is a ___句型", "review": "动物词汇", "game": "介绍动物园朋友"},
    62: {"title": "I like ___.", "topic": "句型I like", "new_words": "I like ___句型", "review": "食物词汇", "game": "食物喜好调查"},
    63: {"title": "I don't like ___.", "topic": "句型否定", "new_words": "I don't like ___句型", "review": "食物+颜色", "game": "挑食小怪兽"},
    64: {"title": "This is + I like 结合", "topic": "句型综合", "new_words": "两个句型结合运用", "review": "所有已知词汇", "game": "购物节目主持人"},
    65: {"title": "第十三周复习", "topic": "句型复习", "new_words": "综合运用", "review": "第61-64课", "game": "玩具店场景"},
    66: {"title": "What is this? 问答", "topic": "问句句型", "new_words": "What is this? / It's a ___.", "review": "This is句型", "game": "神秘箱子猜猜看"},
    67: {"title": "What color is it?", "topic": "颜色问句", "new_words": "What color is it? / It's ___.", "review": "颜色词汇", "game": "颜色猜谜"},
    68: {"title": "问句综合练习", "topic": "问句综合", "new_words": "多种问句综合", "review": "所有词汇", "game": "英语问答擂台"},
    69: {"title": "孩子当提问者", "topic": "反转角色", "new_words": "孩子问AI答", "review": "问句句型", "game": "角色反转"},
    70: {"title": "第十四周复习", "topic": "问句复习", "new_words": "综合场景", "review": "第66-69课", "game": "博物馆讲解员"},
    71: {"title": "I want ___ please.", "topic": "请求句型", "new_words": "I want ___ please.", "review": "食物+数字", "game": "小餐厅点餐"},
    72: {"title": "Can I have ___?", "topic": "礼貌请求", "new_words": "Can I have ___?", "review": "I want句型", "game": "礼貌请求练习"},
    73: {"title": "How much is it?", "topic": "购物句型", "new_words": "How much is it?（简单版）", "review": "数字+食物", "game": "玩具店购物"},
    74: {"title": "I want + 数字", "topic": "数量表达", "new_words": "I want + 数字组合", "review": "数字+请求", "game": "买几个苹果"},
    75: {"title": "第十五周综合", "topic": "购物复习", "new_words": "超市购物完整场景", "review": "第71-74课", "game": "超市购物"},
    76: {"title": "How many?", "topic": "数量问句", "new_words": "How many? / There are___.", "review": "数字1-10", "game": "数数游戏"},
    77: {"title": "数字11-15", "topic": "进阶数字", "new_words": "Eleven, Twelve, Thirteen, Fourteen, Fifteen", "review": "数字1-10", "game": "进阶数数"},
    78: {"title": "数字16-20", "topic": "进阶数字", "new_words": "Sixteen, Seventeen, Eighteen, Nineteen, Twenty", "review": "数字11-15", "game": "更大的数字"},
    79: {"title": "数字综合游戏", "topic": "数字总复习", "new_words": "数字1-20综合", "review": "数字1-20", "game": "宝藏数量猜猜猜"},
    80: {"title": "第四阶段大庆典", "topic": "阶段总结", "new_words": "5大句型综合展示", "review": "第61-79课", "game": "句型大舞台"},
    81: {"title": "早晨起床", "topic": "一天的时光", "new_words": "Good morning! / Time to wake up! / I'm hungry!", "review": "日常问候", "game": "起床情景"},
    82: {"title": "吃早饭", "topic": "一天的时光", "new_words": "What's for breakfast? / I want eggs please.", "review": "食物+早晨", "game": "早餐情景"},
    83: {"title": "上学去", "topic": "一天的时光", "new_words": "Time for school! / Bye Mom!", "review": "早晨+告别", "game": "上学情景"},
    84: {"title": "放学回家", "topic": "一天的时光", "new_words": "I'm home! / How was school? / It was fun!", "review": "上学+问候", "game": "回家情景"},
    85: {"title": "晚安时间", "topic": "一天的时光", "new_words": "Good night! / Sweet dreams! / I love you!", "review": "一天全部", "game": "晚安情景"},
    86: {"title": "今天天气怎么样", "topic": "天气季节", "new_words": "What's the weather? / It's sunny/rainy/cloudy.", "review": "日常表达", "game": "天气播报"},
    87: {"title": "冷和热", "topic": "天气季节", "new_words": "It's hot! / It's cold! / I need a jacket.", "review": "天气词汇", "game": "穿衣服游戏"},
    88: {"title": "四季简介", "topic": "天气季节", "new_words": "Spring / Summer / Autumn / Winter", "review": "天气+冷热", "game": "四季图片"},
    89: {"title": "天气预报小主持", "topic": "天气季节", "new_words": "Today's weather is___ / Tomorrow will be ___", "review": "天气+季节", "game": "小气象员播报"},
    90: {"title": "天气综合游戏", "topic": "天气复习", "new_words": "天气角色扮演综合", "review": "第86-89课", "game": "小气象员"},
    91: {"title": "教室里的东西", "topic": "在学校", "new_words": "Book / Pencil / Chair / Table / Bag", "review": "天气", "game": "教室找东西"},
    92: {"title": "跟老师说", "topic": "在学校", "new_words": "Good morning teacher! / May I go to the toilet?", "review": "教室词汇", "game": "课堂用语"},
    93: {"title": "跟同学玩", "topic": "在学校", "new_words": "Let's play! / Can I join? / That's fun!", "review": "学校词汇", "game": "课间游戏"},
    94: {"title": "上课了", "topic": "在学校", "new_words": "Open your book. / Listen carefully. / Very good!", "review": "学校场景", "game": "小老师游戏"},
    95: {"title": "学校综合场景", "topic": "学校复习", "new_words": "一天学校生活完整对话", "review": "第91-94课", "game": "学校一天"},
    96: {"title": "生日快乐！", "topic": "生日派对", "new_words": "Happy birthday! / How old are you? / I'm six!", "review": "学校", "game": "生日派对"},
    97: {"title": "生日蛋糕", "topic": "生日派对", "new_words": "Make a wish! / Blow the candles! / Yummy!", "review": "生日祝福", "game": "许愿吹蜡烛"},
    98: {"title": "收礼物", "topic": "生日派对", "new_words": "Thank you! / I love it! / It's so cute!", "review": "派对词汇", "game": "拆礼物"},
    99: {"title": "邀请朋友", "topic": "生日派对", "new_words": "Come to my party! / See you Saturday!", "review": "派对全部", "game": "写邀请函"},
    100: {"title": "第100课里程碑！", "topic": "阶段总结", "new_words": "综合表演庆祝", "review": "第81-99课", "game": "综合表演"},
    101: {"title": "小熊找苹果", "topic": "故事听说", "new_words": "颜色+数字+食物 故事", "review": "颜色/数字/食物", "game": "听故事用中文复述"},
    102: {"title": "小猫的朋友们", "topic": "故事听说", "new_words": "动物+家庭+打招呼 故事", "review": "动物/家庭/打招呼", "game": "故事填空"},
    103: {"title": "下雨天的小狗", "topic": "故事听说", "new_words": "天气+衣物+情绪 故事", "review": "天气/身体", "game": "故事问答"},
    104: {"title": "生日派对大冒险", "topic": "故事听说", "new_words": "综合所有主题 故事", "review": "全部主题", "game": "孩子尝试讲故事"},
    105: {"title": "我来编故事", "topic": "故事创作", "new_words": "自由创作", "review": "全部主题", "game": "孩子主导AI辅助"},
    106: {"title": "我是服务员", "topic": "角色扮演餐厅", "new_words": "Welcome! / What do you want? / Here you go!", "review": "食物+请求", "game": "服务员角色"},
    107: {"title": "我是顾客", "topic": "角色扮演餐厅", "new_words": "I want___please. / How much? / Thank you!", "review": "服务员用语", "game": "顾客角色"},
    108: {"title": "完整点餐流程", "topic": "角色扮演餐厅", "new_words": "服务员+顾客完整对话", "review": "第106-107课", "game": "完整对话"},
    109: {"title": "遇到问题", "topic": "角色扮演餐厅", "new_words": "Sorry, we don't have___. / We have___instead.", "review": "餐厅对话", "game": "问题处理"},
    110: {"title": "开餐厅大挑战", "topic": "角色扮演餐厅", "new_words": "孩子自主完成全流程", "review": "第106-109课", "game": "全流程挑战"},
    111: {"title": "身体不舒服", "topic": "角色扮演医生", "new_words": "I don't feel well. / I have a cold.", "review": "身体部位", "game": "说症状"},
    112: {"title": "说症状", "topic": "角色扮演医生", "new_words": "My head hurts. / I have a tummy ache.", "review": "不舒服表达", "game": "描述症状"},
    113: {"title": "看医生", "topic": "角色扮演医生", "new_words": "Open your mouth. / Take this medicine.", "review": "症状表达", "game": "医生问诊"},
    114: {"title": "好起来了！", "topic": "角色扮演医生", "new_words": "I feel better now! / Thank you doctor!", "review": "医生场景", "game": "康复情景"},
    115: {"title": "医生角色扮演", "topic": "角色扮演医生", "new_words": "孩子当医生AI当病人", "review": "第111-114课", "game": "角色互换"},
    116: {"title": "词汇大闯关", "topic": "毕业总复习", "new_words": "6个主题词汇全复习", "review": "全部词汇", "game": "词汇闯关"},
    117: {"title": "句型大舞台", "topic": "毕业总复习", "new_words": "5大句型综合表演", "review": "全部句型", "game": "句型表演"},
    118: {"title": "对话大挑战", "topic": "毕业总复习", "new_words": "孩子主导10分钟完整英语对话", "review": "全部内容", "game": "自由对话"},
    119: {"title": "我的英语故事", "topic": "毕业总复习", "new_words": "孩子自己编一个英语小故事", "review": "全部内容", "game": "故事创作"},
    120: {"title": "毕业庆典！", "topic": "毕业总结", "new_words": "AI颁发英语小达人认证", "review": "第1-119课全部", "game": "毕业典礼"},
}
